### ISSUE TITLE
JointJS name seems to be taken

### ISSUE THREAD

**Issue by zaadjis** [pothibo/observejs#6]
https://encrypted.google.com/search?hl=en&q=jointjs
http://www.jointjs.com/

Might want to rename to avoid confusion.

**Comment by pothibo** [comment]
You are right and I will change it. However, I'm not going to rush for a new name just yet as the version is 0.0.x (unstable). And since the name of the library has some impacts on development (You need to access the global's constant to bind a class), I'll wait until I'm definitive with a new name.

If you, or any other people have an idea about a new name, please let me know here.

**Comment by pothibo** [comment]
Observerjs could be a good name. Seems to be vacant in rubygems & [observerjs.com](http://observerjs.com)

**Comment by pothibo** [comment]
Chose observejs ;) I already bought observejs.io and reserved RubyGem's name.

Thank you!
